IHK_Probe_Projekt/Models/Warenkorb.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IHK_Probe_Projekt.Models
{
    public class Warenkorb
    {
        public int Id { get; set; }
        //public int KundenId {get;set;}
        public decimal Total { get; set; }

        public virtual ICollection<Artikel> Artikeln { get; set; }

        public Warenkorb()
        {
            Artikeln = new HashSet<Artikel>();
        }

    }
}

IHK_Probe_Projekt/Controllers/KundeWarenkorbController.cs
using IHK_Probe_Projekt.Models;
using IHK_Probe_Projekt.Session;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IHK_Probe_Projekt.Controllers
{
    public class KundeWarenkorbController : Controller
    {
        //string sessionId = Request.Properties[SessionIdHandler.SessionIdToken] as string;
        private KaffeeContext _db = new KaffeeContext();

        // GET: KundeWarenkorb
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddItem()
        {
            Kunde kunde;
            var artikel = Session["artikel"] as Artikel;
            kunde = Session["user"] as Kunde;
            if (artikel != null)
            {
                ArtikelWarenkorb artikelWarenkorb = new ArtikelWarenkorb();
                artikelWarenkorb.ArtikelId = artikel.Id;
                artikelWarenkorb.WarenkorbId = kunde.Warenkorb.Id;
                _db.ArtikelWarenkorb.Add(artikelWarenkorb);
                _db.SaveChanges();
            }
            return RedirectToAction("warenkorb", kunde);
        }

        [HttpPost]
        public ActionResult AddItem(string name)
        {
            Kunde kunde;
            var artikel = _db.Artikeln.FirstOrDefault(a => a.Name == name);
            if (Session["user"] == null)
            {
                Session["artikel"] = artikel;
                return View("login");
            }
            else
            {
                kunde = Session["user"] as Kunde;
                ArtikelWarenkorb artikelWarenkorb = new ArtikelWarenkorb();
                artikelWarenkorb.ArtikelId = artikel.Id;
                artikelWarenkorb.WarenkorbId = kunde.Warenkorb.Id;
                _db.ArtikelWarenkorb.Add(artikelWarenkorb);
                _db.SaveChanges();
            }
            return RedirectToAction("warenkorb", kunde);
        }

        public ActionResult Warenkorb()
        {
            if (Session["user"] == null)
            {
                return View("login");
            }
            Kunde kunde = Session["user"] as Kunde;
            var list = _db.ArtikelWarenkorb.Where(x => x.WarenkorbId == kunde.Warenkorb.Id).ToList();
            kunde.Warenkorb.Artikeln.Clear();
            foreach (var item in list)
            {
                Artikel artikel = _db.Artikeln.FirstOrDefault(x => x.Id == item.ArtikelId);
                kunde.Warenkorb.Artikeln.Add(artikel);
            }
            return View(kunde);
        }

        [HttpPost]
        public ActionResult Warenkorb(FormCollection formCollection)
        {
            Kunde kunde = Session["user"] as Kunde;
            Bestellung bestellung = new Bestellung();
            bestellung.KundeId = kunde.Id;
            _db.Bestellungen.Add(bestellung);
            _db.SaveChanges();
            foreach (var item in kunde.Warenkorb.Artikeln)
            {
                ArtikelBestellung artikelBestellung = new ArtikelBestellung
                {
                    ArtikelId = item.Id,
                    BestellungId = bestellung.Id,
                    KundeId = kunde.Id
                };
                _db.ArtikelBestellung.Add(artikelBestellung);
                _db.SaveChanges();
                bestellung.Total += item.Preis;
                //bestellung.Artikeln.Add(item);
                RedirectToAction("PutBestellung", "Bestellung", (bestellung.Id, bestellung));
                _db.SaveChanges();
            }

            kunde.Bestellungen.Add(bestellung);
            Session["bestellung"] = bestellung;
            return RedirectToAction("checkout");
        }

        public ActionResult Checkout()
        {
            Kunde kunde = Session["user"] as Kunde;
            Bestellung bestellung = Session["bestellung"] as Bestellung;
            var bestellungId = kunde.Bestellungen.Max(x => x.Id);
            var list = _db.ArtikelBestellung.Where(ab => ab.BestellungId == bestellungId).ToList();
            List<Artikel> artikeln = new List<Artikel>();
            foreach (var item in list)
            {
                var artikel = _db.Artikeln.FirstOrDefault(a => a.Id == item.ArtikelId);
                artikeln.Add(artikel);
            }
            ViewBag.Kunde = kunde;
            ViewBag.list = artikeln;
            ViewBag.Total = bestellung.Total;
            ViewBag.KundenId = kunde.Id;
            ViewBag.BestellungId = bestellung.Id;

            kunde.Warenkorb.Artikeln.Clear();

            bool check = true;

            while (check)
            {
                var result = _db.ArtikelWarenkorb.FirstOrDefault(a => a.WarenkorbId == kunde.Warenkorb.Id);
                if (result != null)
                {
                    _db.ArtikelWarenkorb.Remove(result);
                    _db.SaveChanges();
                }
                else check = false;
            }
            return View();
        }

        public ActionResult Login()
        {
            ViewBag.Error = "";
            return View();
        }

        [HttpPost]
        public ActionResult Login(string Email, string Password)
        {
            string pw = HashHelper.CreateHash(Password);
            var kunde = _db.Kunden.FirstOrDefault(k => k.Email == Email && k.Password == pw);
            if (kunde != null)
            {
                Session["user"] = kunde;
                return RedirectToAction("AddItem");
            }
            ViewBag.Error = "Die Email/Passwort Combination ist falsch";
            return View();
        }

        public ActionResult NeuerKunde()
        {
            ViewBag.Error = "";
            return View();
        }

        [HttpPost]
        public ActionResult NeuerKunde(Kunde kunde)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (_db.Kunden.FirstOrDefault(k => k.Email == kunde.Email) != null)
                    {
                        ViewBag.Error = "Die Emailaddresse ist schon registriert";
                        return View();
                    }
                    kunde.Password = HashHelper.CreateHash(kunde.Password);
                    kunde.Warenkorb = new Warenkorb();
                    _db.Kunden.Add(kunde);
                    _db.SaveChanges();
                    Session["user"] = kunde;
                }
                catch (DbUpdateConcurrencyException)
                {

                }
            }
            return RedirectToAction("warenkorb");
        }
    }
}

IHK_Probe_Projekt/Controllers/WarenkorbController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;
using System.Web.Http.Description;
using IHK_Probe_Projekt.Models;

namespace IHK_Probe_Projekt.Controllers
{
    [EnableCors("*", "*", "*")]
    public class WarenkorbController : ApiController
    {
        private KaffeeContext db = new KaffeeContext();

        // GET: api/Warenkorb
        public IQueryable<Warenkorb> GetWarenkorb()
        {
            return db.Warenkorb;
        }

        // GET: api/Warenkorb/5
        [ResponseType(typeof(Warenkorb))]
        public IHttpActionResult GetWarenkorb(int id)
        {
            Warenkorb warenkorb = db.Warenkorb.Find(id);
            if (warenkorb == null)
            {
                return NotFound();
            }

            return Ok(warenkorb);
        }

        // PUT: api/Warenkorb/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutWarenkorb(int id, Warenkorb warenkorb)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != warenkorb.Id)
            {
                return BadRequest();
            }

            db.Entry(warenkorb).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!WarenkorbExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Warenkorb
        [ResponseType(typeof(Warenkorb))]
        public IHttpActionResult PostWarenkorb(Warenkorb warenkorb)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Warenkorb.Add(warenkorb);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = warenkorb.Id }, warenkorb);
        }

        // DELETE: api/Warenkorb/5
        [ResponseType(typeof(Warenkorb))]
        public IHttpActionResult DeleteWarenkorb(int id)
        {
            Warenkorb warenkorb = db.Warenkorb.Find(id);
            if (warenkorb == null)
            {
                return NotFound();
            }

            db.Warenkorb.Remove(warenkorb);
            db.SaveChanges();

            return Ok(warenkorb);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool WarenkorbExists(int id)
        {
            return db.Warenkorb.Count(e => e.Id == id) > 0;
        }
    }
}

IHK_Probe_Projekt/Views/KundeWarenkorb/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";
}

<br />
<h2>Checkout</h2>

<p>
    @ViewBag.Kunde.Vorname @ViewBag.Kunde.Nachname <br />
    @ViewBag.Kunde.Strasse @ViewBag.Kunde.Hausnr <br />
    @ViewBag.Kunde.PLZ @ViewBag.Kunde.Ort <br />
    @ViewBag.Kunde.Email <br />
    @ViewBag.Kunde.TelefonNr
</p>

<p>Sie haben die folgenden Ware erfolgreich bestellt:</p>
<table id="table" class="table table-success table-striped">
    <tbody>
        <tr>
            <th scope="col">Artikel Name</th>
            <th scope="col">Menge</th>
            <th scope="col">Preis</th>
            <th scope="col">Total</th>
        </tr>
        @foreach (var item in ViewBag.list)
        {
            if (item != null)
            {
                <tr>
                    <td>@item.Name</td>
                    <td id="menge + @item.Id">1</td>
                    <td id="preis_@item.Id">@item.Preis</td>
                    <td id="total_@item.Id">@item.Preis</td>
                </tr>
            }
        }
        <tr>
            <td></td>
            <td></td>
            <td><b>Total</b></td>
            <td>@ViewBag.Total</td>
        </tr>
    </tbody>
</table>
<p>Bezahlung ist nur gegen Vorauskasse möglich. Wir bemühen uns, Ihnen in der nahen Zukunft auch andere Zahlungsmethoden zur Verfügung stellen zu können.<br />
    Firma: Kirchheim Kaffee<br />
    Bank: DE30 3456 1234 0000 0000 1234 56<br />
    Verwendungszweck: Kunden-nr @ViewBag.KundenId, Bestellungsnummer @ViewBag.BestellungId<br />
    <br />
    Nach dem Zahlungseingang schicken wir Ihnen die Ware zu.
    </p>

IHK_Probe_Projekt/Views/KundeWarenkorb/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<br />
<h2>Login</h2>
@if (ViewBag.Error != "")
{<label class="alert-danger">@ViewBag.Error</label>}
<form action="~/KundeWarenkorb/Login" method="post">
    <div class="form-group">
        <input type="text" name="Email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" name="Password" placeholder="Password" />
    </div>
    <input type="submit" class="btn btn-primary" value="Login" />
</form>
<form action="~/KundeWarenkorb/NeuerKunde" method="get">
    <label>Noch nicht registriert?</label>
    <input type="submit" class="btn btn-primary" value="Registrieren" />
</form>

IHK_Probe_Projekt/Views/KundeWarenkorb/NeuerKunde.cshtml
@model IHK_Probe_Projekt.Models.Kunde

@{
    ViewBag.Title = "Neuer Kunde";
}
<br />
<h2>Anmeldung</h2>
@if (ViewBag.Error != "")
{<label class="alert-danger">@ViewBag.Error</label>}

@using (Html.BeginForm("NeuerKunde", "KundeWarenkorb",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-inline">
            @Html.LabelFor(model => model.Vorname, htmlAttributes: new { @class = "control-label md-2 sr-only" })
            <div>
                @Html.EditorFor(model => model.Vorname, new { htmlAttributes = new { @class = "form-control", @placeholder = "Vorname" } })
                @Html.ValidationMessageFor(model => model.Vorname, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Nachname, htmlAttributes: new { @class = "control-label md-2 sr-only" })
            <div class="m-1">
                @Html.EditorFor(model => model.Nachname, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nachname" } })
                @Html.ValidationMessageFor(model => model.Nachname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-inline">
            @Html.LabelFor(model => model.Strasse, htmlAttributes: new { @class = "control-label col-md-2 sr-only" })
            <div>
                @Html.EditorFor(model => model.Strasse, new { htmlAttributes = new { @class = "form-control", @placeholder = "Straße" } })
                @Html.ValidationMessageFor(model => model.Strasse, "", new { @class = "text-danger" })
            </div>
            @Html.LabelFor(model => model.Hausnr, htmlAttributes: new { @class = "control-label col-md-2 sr-only" })
            <div class="m-1">
                @Html.EditorFor(model => model.Hausnr, new { htmlAttributes = new { @class = "form-control col-sm-5", @placeholder = "Hausnr." } })
                @Html.ValidationMessageFor(model => model.Hausnr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-inline">
            @Html.LabelFor(model => model.PLZ, htmlAttributes: new { @class = "control-label col-md-2 sr-only" })
            <div>
                @Html.EditorFor(model => model.PLZ, new { htmlAttributes = new { @class = "form-control col-sm-5", @placeholder = "PLZ" } })
                @Html.ValidationMessageFor(model => model.PLZ, "", new { @class = "text-danger", @placeholder = "PLZ" })
            </div>
            @Html.LabelFor(model => model.Ort, htmlAttributes: new { @class = "control-label col-md-2 sr-only" })
            <div class="m-1">
                @Html.EditorFor(model => model.Ort, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ort" } })
                @Html.ValidationMessageFor(model => model.Ort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2 sr-only" })
            <div>
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelefonNr, htmlAttributes: new { @class = "control-label col-md-2 sr-only" })
            <div>
                @Html.EditorFor(model => model.TelefonNr, new { htmlAttributes = new { @class = "form-control", @placeholder = "Telefonnummer" } })
                @Html.ValidationMessageFor(model => model.TelefonNr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @type="password" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <input type="submit" value="Registrieren" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IHK_Probe_Projekt/Views/KundeWarenkorb/Warenkorb.cshtml
@{
    ViewBag.Title = "Warenkorb";
}

<br />
<h2>Warenkorb</h2>
<table id="table" class="table table-success table-striped">
    <tbody>
        <tr>
            <th scope="col">Artikel Name</th>
            <th scope="col">Menge</th>
            <th scope="col">Preis</th>
            <th scope="col">Total</th>
            <th scope="col">Menge Bearbeiten</th>
        </tr>
        @foreach (var item in Model.Warenkorb.Artikeln)
        {
            if (item != null)
            {
                <tr>
                    <td>@item.Name</td>
                    <td id="menge + @item.Id">1</td>
                    <td id="preis_@item.Id">@item.Preis</td>
                    <td id="total_@item.Id">@item.Preis</td>
                    <td>
                        <button id="@item.Id" class="btn btn-success m-1" onclick="add(this.id)">+</button>
                        <button id="@item.Id" class="btn btn-success m-1" onclick="subtract(this.id)">-</button>
                    </td>
                </tr>
            }
        }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td id="total"></td>
            <td></td>
        </tr>
    </tbody>
</table>
<form action="~/KundeWarenkorb/Warenkorb" method="post">
    <input type="text" name="item_1" hidden />
    <input type="text" name="item_2" hidden />
    <input type="text" name="item_3" hidden />
    <input type="text" name="item_4" hidden />
    <input type="submit" class="btn btn-primary" value="Checkout" />
</form>
<script type="text/javascript">
    function add(clicked_id) {
        var menge = document.getElementById("menge + " + clicked_id)
        menge.innerHTML = parseInt(menge.innerHTML) + 1

        var preis = document.getElementById("preis_" + clicked_id)
        var subtotal = document.getElementById("total_" + clicked_id)
        subtotal.innerHTML = (parseFloat(preis.innerHTML) * parseInt(menge.innerHTML)).toFixed(2)

        computeTableColumnTotal("table", 3)

        document.getElementById("item_" + clicked_id).setAttribute('value', menge.innerHTML);
    }

    function subtract(clicked_id) {
        var menge = document.getElementById("menge + " + clicked_id)

        if (parseInt(menge.innerHTML) > 0) {
            menge.innerHTML = parseInt(menge.innerHTML) - 1

            var preis = document.getElementById("preis_" + clicked_id)
            var subtotal = document.getElementById("total_" + clicked_id)
            subtotal.innerHTML = (parseFloat(preis.innerHTML) * parseInt(menge.innerHTML)).toFixed(2)
        }
        computeTableColumnTotal("table", 3)
    }

    function computeTableColumnTotal(tableId, colNumber) {
        // find the table with id attribute tableId
        // return the total of the numerical elements in column colNumber
        // skip the top row (headers) and bottom row (where the total will go)
        var result = 0;
        try {
            var tableElem = window.document.getElementById(tableId);
            var tableBody = tableElem.getElementsByTagName("tbody").item(0);
            var i;
            var howManyRows = tableBody.rows.length;
            for (i = 1; i < (howManyRows - 1); i++) // skip first and last row (hence i=1, and howManyRows-1)
            {
                var thisTrElem = tableBody.rows[i];
                var thisTdElem = thisTrElem.cells[colNumber];
                var thisTextNode = thisTdElem.childNodes.item(0);

                // try to convert text to numeric
                var thisNumber = parseFloat(thisTextNode.data);
                // if you didn't get back the value NaN (i.e. not a number), add into result
                if (!isNaN(thisNumber))
                    result += thisNumber;
            } // end for
        } // end try
        catch (ex) {
            window.alert("Exception in function computeTableColumnTotal()\n" + ex);
            result = 0;
        }
        finally {
            var total = document.getElementById("total")
            total.innerHTML = result.toFixed(2)
        }
    }
</script>